[project]
name = "simple-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.28.1",
    "mypy>=2.1.0",
    "python-dotenv>=1.2.2",
    "spotipy>=2.26.0",
]

[tool.mypy]
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "spotipy.*"
ignore_missing_imports = true

